name: Build Docker App Image and Push it to Docker Hub

on:
  push:
    paths:
      - .github/workflows/laraveloctane-alpine.arm64.yml
      - laraveloctane-alpine.arm64
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ arm64 ]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push app
        uses: docker/build-push-action@v4
        with:
          file: "laraveloctane-alpine.arm64"
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/larvoct:arm64-${{ github.run_number }}, ${{ secrets.DOCKER_USERNAME }}/larvoct:arm64-alpine:latest
